name: NuGet

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v2
    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: |
          dotnet restore
      
      - name: Build
        run: |
          dotnet build --configuration Release --no-restore
      
      - name: Pack
        run: |
          dotnet pack --configuration Release -o target/

      - uses: actions/upload-artifact@v1
        with:
          name: target
          path: target

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/field-works/index.json" -n "github" -u kkajita -p ${{secrets.NUGET_PACKAGE}} --store-password-in-clear-text
          dotnet nuget push "target/*.nupkg" --api-key ${{secrets.NUGET_PACKAGE}} --source "github" --skip-duplicate